services:
  - type: web
    name: unilink-api
    env: node
    region: oregon
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        value: https://seu-front.vercel.app
